<?php
/**
 * Benissimo Magento Theme
 *
 * @category    design
 * @package     benissimo_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php if ($block_html = $this->getChildHtml('cms_footer_social')): ?>
<div class="block footer-social-block"><?php echo $block_html ?></div>
<?php endif ?>
