<?php
/**
 * Benissimo Magento Theme
 *
 * @category    design
 * @package     benissimo_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="form-add">
    <h4><?php echo $this->__('Write Your Own Review') ?></h4>
    <?php if ($this->getAllowWriteReviewFlag()): ?>
    <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
        <fieldset>
            <?php echo $this->getChildHtml('form_fields_before')?>
            <?/*<h3><?php echo $this->__("You're reviewing:"); ?> <span><?php echo $this->htmlEscape($this->getProductInfo()->getName()) ?></span></h3>*/?>
            <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
                <?/*<h4><?php echo $this->__('How do you rate this product?') ?> <em class="required">*</em></h4>*/?>
                <div id="product-review-add" class="evaluation">
                    <?php foreach ($this->getRatings() as $_rating): ?>
                        <div class="evaluation-box">
                            <strong><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></strong><em>*</em>
                        <?php foreach ($_rating->getOptions() as $_option): ?>
                            <input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio" />
                        <?php endforeach; ?>
                        </div>
                    <?php endforeach; ?>
                    <span id="input-message-box"></span>
                    <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                </div>
            <?php endif; ?>
                <ul class="form-list">
                    <li class="nickname">
                        <label for="nickname_field" class="required"><strong><?php echo $this->__('Nickname') ?></strong><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getNickname()) ?>" />
                        </div>
                    </li>
                    <li class="your_review">
                        <label for="summary_field" class="required"><strong><?php echo $this->__('Summary of Your Review') ?></strong><em>*</em></label>
                        <div class="input-box">
                            <input type="text" name="title" id="summary_field" class="input-text required-entry" value="<?php echo $this->htmlEscape($data->getTitle()) ?>" />
                        </div>
                    </li>
                    <li class="text_review">
                        <label for="review_field" class="required"><strong><?php echo $this->__('Review') ?></strong><em>*</em></label>
                        <div class="input-box">
                            <textarea name="detail" id="review_field" cols="5" rows="3" class="required-entry"><?php echo $this->htmlEscape($data->getDetail()) ?></textarea>
                            <i>Note: HTML is not translated!</i>
                        </div>
                    </li>
                </ul>
            </fieldset>
            <div class="buttons-set">
                <button type="submit" title="<?php echo $this->__('Submit Review') ?>" class="button"><span><span><?php echo $this->__('Submit Review') ?></span></span></button>
            </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('review-form');
        Validation.addAllThese(
        [
               ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above') ?>', function(v) {
                    var ratings = $('product-review-add').select('.evaluation-box');
                    var inputs;
                    var error = 1;

                    for( var j=0; j < ratings.length; j++ ) {
                        var rating = ratings[j];
                        if( j > 0 ) {
                            inputs = rating.select('input');

                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }

                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]>
    </script>
    <?php else: ?>
    <p class="review-nologged" id="review-form">
        <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
    </p>
    <?php endif ?>
</div>
