<?php
/**
 * Benissimo Magento Theme
 *
 * @category    design
 * @package     benissimo_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Column products list template
 *
 * @see Mage_Catalog_Block_Product_List and ItemBridge_Theme_Block_Product_List_Featured
 */
?>
<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $ibtheme = $this->helper('ibtheme');
?>
<?php if ( ! $_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<ul class="column-products-list">
<?php foreach ($_productCollection as $_product): ?>
    <li class="item product <?php echo $ibtheme->getProductClasses($_product) ?>">
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(1350); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
        <div class="product-details">
            <p class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></p>
            <?php if ($_product->getRatingSummary())
                echo $this->getReviewsSummaryHtml($_product, 'short'); ?>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <?php if ($this->helper('wishlist')->isAllow()): ?>
                <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
            <?php endif ?>
        </div>
    </li>
<?php endforeach ?>
</ul>
<script type="text/javascript">decorateGeneric($$('ul.column-products-list > li'), ['odd', 'even', 'first', 'last'])</script>
<?php endif ?>
