<?php
/**
 * Benissimo Magento Theme
 *
 * @category    design
 * @package     benissimo_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Featured product list template
 *
 * @see ItemBridge_Theme_Block_Product_List_Featured
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $ibtheme = $this->helper('ibtheme');
    $_collectionSize = $_productCollection->count();
    $_columnCount = $this->getColumnCount();
    $i = 0;
?>
<div class="widget widget-featured-products">
<?php if( ! $_collectionSize): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <ul class="products-grid">
        <?php foreach ($_productCollection as $_product): ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> <?php echo $ibtheme->getProductClasses($_product) ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210); ?>" width="210" height="210" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <ul class="add-to-links">
                        <?php if($_product->isSaleable()): ?>
                            <li><a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="link-cart"><?php echo $this->__('Add to Cart') ?></a></li>
                        <?php else: ?>
                            <li><span class="link-cart availability out-of-stock" title="<?php echo $this->__('Out of stock') ?>"><?php echo $this->__('Add to Cart') ?></span></li>
                        <?php endif ?>
                        <?php if ($this->helper('wishlist')->isAllow()): ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif ?>
                    </ul>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>
<?php endif ?>
</div>
