<?php
/**
 * Benissimo Magento Theme
 *
 * @category    design
 * @package     benissimo_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>

<?php $_items = $this->getReviewsCollection()->getItems() ?>

<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)): ?>
        <?/*<h4><?php echo $this->__('Customer Reviews') ?></h4>*/?>
        <?php echo $this->getChildHtml('toolbar') ?>

        <ul class="comments">
        <?php foreach ($_items as $_review):?>
            <li>
                <div class="title"><?php echo $this->htmlEscape($_review->getTitle()) ?></div>
                <div class="author"><?php echo $this->htmlEscape($_review->getNickname()) ?>,</div>
                <div class="date"><?php echo $this->formatDate($_review->getCreatedAt()) ?></div>
                <div>
                    <?php $_votes = $_review->getRatingVotes(); ?>
                    <?php if (count($_votes)): ?>
                        <div class="evaluation">
                            <?php foreach ($_votes as $_vote): ?>
                            <div class="evaluation-box">
                                <strong><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></strong>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <div class="clear"></div>
                        </div>
                    <?php endif ?>
                    <p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?></p>
                </div>
            </li>
        <?php endforeach ?>
        </ul>
        <?php echo $this->getChildHtml('toolbar') ?>
    <?php endif ?>

    <?php echo $this->getChildHtml('review_form') ?>
</div>
