<?php
/**
 * Benissimo Magento Theme
 *
 * @category    design
 * @package     benissimo_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()): ?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif ?>
        <span class="amount"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></span>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><?php echo $this->__('Add Your Review') ?></p>
<?php endif ?>
