<?php
/**
 * Benissimo Magento Theme
 *
 * @category    design
 * @package     benissimo_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<div class="clear"></div>
<div class="footer-container">
    <footer>
        <div class="f_navigation">
            <div class="container_12">
                <?php echo $this->getChildHtml() ?>
            </div><!-- .container_12 -->
        </div><!-- .f_navigation -->
        
        <div class="f_info">
            <div class="container_12">
                <div class="grid_6">
                    <p class="copyright"><?php echo $this->getCopyright() ?></p>
                </div><!-- .grid_6 -->

                <div class="clear"></div>
            </div><!-- .container_12 -->
        </div><!-- .f_info -->
    </footer>
</div>
