<?php
/**
 * Benissimo Magento Theme
 *
 * @category    design
 * @package     benissimo_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>
<?php
/**
 * Category image template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_category  = $this->getCurrentCategory();
    $_image_url = $_category->getImageUrl();
?>
<?php if ($_image_url): ?>
<div class="block category-image-block"><img src="<?php echo $_image_url ?>" alt="<?php echo $this->htmlEscape($_category->getName()) ?>" title="<?php echo $this->htmlEscape($_category->getName()) ?>"/></div>
<?php endif ?>
