<?php
/**
 * Benissimo Magento Theme
 *
 * @category    design
 * @package     benissimo_default
 * @copyright   Copyright (c) 2012 InfoStyle (http://infostyle.com.ua)
 * @license     http://themeforest.net/licenses/regular_extended ThemeForest Regular & Extended License
 */
?>

<?php
    $_product = $this->getProduct();
    $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product);
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
?>

<div class="product-extra-actions">
    <ul class="add-to-links">
    <?php if ($this->helper('wishlist')->isAllow()): ?>
        <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
    <?php endif ?>
    <?php if($_compareUrl): ?>
        <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
    <?php endif ?>
    </ul>
</div>
